# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: pretty-format-json
    args:
    - --autofix
  - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.8
